# -*- coding: utf-8 -*-
"""telescope-site-mapper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXV6oYO-vbduoCFhvcKa8ZIxXfETcVXI
"""

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
import math


# Leer el archivo de texto
datos = []
with open("NE-F1_28-jun-2023_091642.txt", "r") as file:
    # Saltar la primera línea (encabezado)
    next(file)
    for line in file:
        hora, azimuth, elevacion, potencia = line.strip().split()
        datos.append((hora, float(azimuth), float(elevacion), float(potencia)))

# Obtener las listas separadas para cada columna

horas = [dato[0] for dato in datos]
azimuths = [dato[1] for dato in datos]
elevaciones = [dato[2] for dato in datos]
potencias = [dato[3] for dato in datos]


# Asignar colores a las intensidades
intensidades = potencias
colormap = mcolors.LinearSegmentedColormap.from_list("", ["purple", "blue", "turquoise","green", "yellow", "red"])
norm = mcolors.Normalize(vmin=min(intensidades), vmax=max(intensidades))
colores = [colormap(norm(intensidad)) for intensidad in intensidades]

# Graficar el espectro en microondas con colores superpuestos

plt.scatter(azimuths, elevaciones, c=colores, linewidth=9)
plt.scatter(azimuths, elevaciones, c=colores)
plt.xlabel('Azimuth')
plt.ylabel('Elevación')
plt.title('Espectro en Microondas')
plt.colorbar(label='Intensidad')
plt.show()